Task#99786
aurestic/l10n-spain pull request #21
Opened 2022-07-11 12:35 UTC by almumu

en el módulo del sii de la oca, cuando envían varias facturas a la vez, si una de ellas la devuelven con errores, el resto de facturas se quedan sin el estado del sii guardado, y aparecen como no enviadas, pero en realidad sí lo están. En nuestro módulo del sii de los descuentos globales (nubea_discount_invoice_aeat_sii) ya hicimos el arreglo para que esto no pasara. Hacemos el mismo arreglo para los clientes como los rentacar que no usan los descuentos globales pero sí usan el sii.

2022-07-11 14:11 UTC, zamberjo requested changes
utiliza `self.env.cr.savepoint`

2022-07-12 06:01 UTC, carlosbej2 approved these changes

2022-07-12 11:13 UTC, JordiToledo approved these changes

2022-07-12 11:18 UTC, zamberjo commented on l10n_es_aeat_sii/models/account_invoice.py
> +                        "no se pudo serializar el acceso debido a un update concurrente":
ufffff

2022-07-12 11:18 UTC, zamberjo approved these changes

2022-07-12 11:41 UTC, merged