Primera version QR Verifactu
aurestic/l10n-spain pull request #62
Opened 2024-11-14 13:32 UTC by ozono

Primera versión de la implementación del código QR basada en el documento oficial: [Especificación del Código QR en Facturas](https://www.agenciatributaria.es/static_files/AEAT_Desarrolladores/EEDD/IVA/VERI-FACTU/DetalleEspecificacTecnCodigoQRfactura.pdf).

La implementación se ha hecho tomando como referencia el código existente para TBAI.

### Temas pendientes o a discutir:

1. **Posición del Código QR**: La ubicación del código QR en la factura no cumple al 100% los requisitos especificados. Aunque la posición es clara, no está colocada según se menciona en el documento de especificación.

2. **Tipos de campos para la URL y el QR**: Actualmente, los campos para la URL y el QR se calculan dinámicamente. Sería conveniente almacenarlos de forma persistente (stored), sin embargo, dependen de la agencia, el cual por el momento no está referenciado desde el objeto `account.move` como lo hacen en TBAI.

3. **Tests unitarios pendientes**: Aún no hemos añadido tests unitarios. Una vez se confirme que no hay problemas graves, nos encargaremos de incluir alguno.

Agradecer a todos los implicados en esta implementación, incluidos los responsables del módulo TBAI, por el tiempo y el esfuerzo empleados.

2024-11-19 08:45 UTC, almumu commented
En primer luegar, muchas gracias por la aportación @ozono, he visto alguna cosa que habría que cambiar, te lo pongo en el pr

2024-11-19 08:48 UTC, almumu requested changes

2024-11-19 08:48 UTC, almumu commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +            record.verifactu_enabled = any(self.env.companies.mapped("verifactu_enabled"))
el verifactu_enabled está implementado en:
https://github.com/ozono/l10n-spain/blob/9794ab52202dcbab2fcdb117327a5b86361dd7ff/l10n_es_aeat_verifactu/models/account_move.py#L52
```suggestion
```

2024-11-19 08:48 UTC, almumu commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +                company_vat = company_vat[2:]
en el módulo l10n_es_aeat disponemos de una función que ya devuelve el nif en el formato correcto
https://github.com/ozono/l10n-spain/blob/9794ab52202dcbab2fcdb117327a5b86361dd7ff/l10n_es_aeat/models/res_partner.py#L93
```suggestion
            company_vat = record.company_id.partner_id._parse_aeat_vat_info()[2]
```

2024-11-19 08:48 UTC, almumu commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +                    ("importe", self.amount_total),
```suggestion
                    ("numserie", record.name),
                    ("fecha", record.invoice_date.strftime("%d-%m-%Y")),
                    ("importe", record.amount_total),
```

2024-11-19 09:24 UTC, ljsalvatierra-factorlibre commented
Hola @ozono muchas gracias por la contribución! Estoy con la revisión también, ¿podríais añadir tests unitarios?

2024-11-19 12:07 UTC, ozono commented
Resueltos.

> Hola @ozono muchas gracias por la contribución! Estoy con la revisión también, ¿podríais añadir tests unitarios?



> Hola @ozono muchas gracias por la contribución! Estoy con la revisión también, ¿podríais añadir tests unitarios?

Listos.

2024-11-20 10:33 UTC, ljsalvatierra-factorlibre requested changes

2024-11-20 10:33 UTC, ljsalvatierra-factorlibre commented on l10n_es_aeat_verifactu/tests/test_10n_es_aeat_verifactu.py
> +            "fecha": self.invoice.invoice_date.strftime("%d-%m-%Y"),
Tienes disponible el método `_change_date_format` en `account.move`.

2024-11-20 10:33 UTC, ljsalvatierra-factorlibre commented on l10n_es_aeat_verifactu/tests/test_10n_es_aeat_verifactu.py
> +        self.assertFalse(qr_code, "QR code should not be generated for draft invoices.")
Añadiría una comprobación de que el estado de la factura es borrador.

2024-11-20 11:18 UTC, ozono commented on l10n_es_aeat_verifactu/tests/test_10n_es_aeat_verifactu.py
> +        self.assertFalse(qr_code, "QR code should not be generated for draft invoices.")
Gracias por la sugerencia. Sobre este punto, no estoy del todo de acuerdo. Por lo que entiendo, los tests crean una factura en estado borrador, y desde mi punto de vista, no sería necesario incluir esa comprobación, ya que el estado de la factura parece ser un dato predefinido en este contexto. Además, considero que esa comprobación podría ir más allá del alcance del test. De hecho, en otros tests ya se ejecutan métodos o acciones que asumen un estado específico de la factura sin comprobarlo previamente.

2024-11-20 11:26 UTC, ljsalvatierra-factorlibre requested changes

2024-11-20 11:26 UTC, ljsalvatierra-factorlibre commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +                    ("importe", record.amount_total),
Creo que sería mejor realizar la implementación de un método de obtención de los valores en los modelos que hereden el mixin.

2024-11-20 11:35 UTC, ozono commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +                    ("importe", record.amount_total),
Te refieres a algo como lo que se hace en _get_verifactu_hash_string?

2024-11-20 11:41 UTC, ljsalvatierra-factorlibre commented on l10n_es_aeat_verifactu/models/verifactu_mixin.py
> +                    ("importe", record.amount_total),
Eso es

2024-11-20 12:34 UTC, ljsalvatierra-factorlibre approved these changes

2024-11-20 12:34 UTC, ljsalvatierra-factorlibre commented on l10n_es_aeat_verifactu/views/report_invoice.xml
> +            class="text-center" t-if="o.verifactu_enabled and o.verifactu_qr">
¿Debería ser visible para todo tipo de facturas?

2024-11-20 12:40 UTC, ozono commented on l10n_es_aeat_verifactu/views/report_invoice.xml
> +            class="text-center" t-if="o.verifactu_enabled and o.verifactu_qr">
Por ahora, no, ya que únicamente contiene la URL de validación Veri*Factu. Si en el futuro llegara a incluir información relevante de la factura, entonces sí.

2024-11-26 07:48 UTC, almumu requested changes

2024-11-26 07:48 UTC, almumu commented on l10n_es_aeat_verifactu/models/account_move.py
> +        self.ensure_one()
aquí, si es api.model , habría que quitar el self.ensure.one(),  o quitar el api.model y dejar el self.ensure_one()
```suggestion
    @api.model
    def _get_verifactu_qr_values(self):
        """Get the QR values for the verifactu"""
```

2024-11-27 09:50 UTC, ozono commented on l10n_es_aeat_verifactu/models/account_move.py
> +        self.ensure_one()
Es cierto. No debería ser @api.model, ya que depende de los valores de un registro específico para ofrecer resultados.

2024-11-27 10:02 UTC, ozono commented on l10n_es_aeat_verifactu/models/account_move.py
> +        self.ensure_one()
De la misma manera, no sería adecuado usar @api.model, por ejemplo, en _get_verifactu_hash_string, ya que este método también depende de valores específicos del modelo.

2024-11-28 06:55 UTC, almumu commented on l10n_es_aeat_verifactu/models/account_move.py
> +        self.ensure_one()
tienes razón, hemos actualizado nuestra rama y modificado eso. Tendrás que actualizarte tu rama para que no te salgan conflictos. Con eso ya estaría todo ok para mergear  :)  Buen trabajo

2024-11-28 10:07 UTC, ozono commented
Listo. Está hecho el rebase y un squash para que todo el tema del QR vaya en un commit.

2024-11-28 10:26 UTC, almumu approved these changes

2024-11-28 10:28 UTC, merged